name: Deploy to Azure Container Instances

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/admuse-easy:${{ github.sha }} .
        docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/admuse-easy:${{ github.sha }}
    
    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: admuse-easy-${{ github.sha }}
        image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/admuse-easy:${{ github.sha }}
        registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        name: admuse-easy-container
        location: 'East US'
        environment-variables: |
          NODE_ENV=production
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}