name: Deploy to Azure Web App for Containers

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'Admuse-Easy'
  CONTAINER_REGISTRY: 'admuseeasyregistry.azurecr.io'
  IMAGE_NAME: 'admuseasy'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
    
    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CONTAINER }}
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    - name: Wait for deployment
      run: |
        echo "Waiting for Azure Web App to start with new container..."
        sleep 60
    
    - name: Simple Health Check
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 120
        
        # Simple health check
        if curl -f -m 30 https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health; then
          echo "✅ Deployment successful!"
        else
          echo "⚠️ Health check failed, but deployment may still be starting..."
        fi
        
        echo "🚀 Deployment completed!"
        echo "🌐 Live at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"