name: Deploy to Azure Web App for Containers

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'Admuse-Easy'
  CONTAINER_REGISTRY: 'admuseeasyregistry.azurecr.io'
  IMAGE_NAME: 'admuseasy'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha
          type=raw,value=latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set Azure Web App Container Settings
      run: |
        az webapp config container set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group AdmuseEasy_group \
          --docker-custom-image-name ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --docker-registry-server-url https://${{ env.CONTAINER_REGISTRY }} \
          --docker-registry-server-user ${{ secrets.AZURE_REGISTRY_USERNAME }} \
          --docker-registry-server-password ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Configure App Service Runtime
      run: |
        # Set the app to use Docker container runtime
        az webapp config set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group AdmuseEasy_group \
          --linux-fx-version "DOCKER|${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
    
    - name: Restart Azure Web App
      run: |
        az webapp restart \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group AdmuseEasy_group
    
    - name: Simple Health Check
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 120
        
        # Simple health check
        if curl -f -m 30 https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health; then
          echo "✅ Deployment successful!"
        else
          echo "⚠️ Health check failed, but deployment may still be starting..."
        fi
        
        echo "🚀 Deployment completed!"
        echo "🌐 Live at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"